% Instrumentation and multimodality imaging
% Homework 2
% 2015/2016
% Dual Energy Substraction (student version)

function [soft_tissue, bone_tissue]=DualEnergySubtraction_student(LowEnergyProj,HighEnergyProj, coeff_soft,coeff_bone)

% ------- Implement the equations for dual energy subtraction
soft_tissue=coeff_soft(1)*ones(size(LowEnergyProj))+coeff_soft(2)*LowEnergyProj+...
    coeff_soft(3)*HighEnergyProj+coeff_soft(4)*LowEnergyProj.^2+coeff_soft(5)*HighEnergyProj.^2+...
    coeff_soft(6)*LowEnergyProj.*HighEnergyProj+coeff_soft(7)*LowEnergyProj.^3+...
    coeff_soft(8)*HighEnergyProj.^3;
bone_tissue=coeff_bone(1)*ones(size(LowEnergyProj))+coeff_bone(2)*LowEnergyProj+...
    coeff_bone(3)*HighEnergyProj+coeff_bone(4)*LowEnergyProj.^2+coeff_bone(5)*HighEnergyProj.^2+...
    coeff_bone(6)*LowEnergyProj.*HighEnergyProj+coeff_bone(7)*LowEnergyProj.^3+...
    coeff_bone(8)*HighEnergyProj.^3;
end
